name: Upload Mod Release

on:
  push:
    branches:
      - master
      - '[0-9].+[0-9]+.?[0-9]?'

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mod repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 32

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Test Server
        run: gradle --build-cache --info --stacktrace runGameTestServer

      - name: Update Version
        uses: googleapis/release-please-action@v4
        with:
          target-branch: ${{ github.ref_name }}

      - name: Execute Gradle build
        run: gradle --build-cache --info --stacktrace assemble

      - name: Upload Release
        if: ${{ steps.release.outputs.releases_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./build/libs/*.jar