name: Release tagged build

on:
  push:
    tags: [ '*' ]

jobs:
  release-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mod repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: |
            17
            21
          distribution: 'temurin'
          cache: gradle

      - name: Execute Gradle build
        run: gradle --build-cache --info --stacktrace assemble

      - name: Upload Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload v${{ github.ref_name }} ./build/libs/*.jar